server:
  servlet:
    context-path: /tct

spring:
  application:
    name: MyFirstRestApp
  datasource:
    url: jdbc:sqlserver://185.158.2.148:54321;database=AdventureWorks;encrypt=true;trustServerCertificate=true;
    username: sa
    password: sql@TCT5*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate.default_schema: Person
    hibernate:
      ddl-auto: none
    show-sql: true

myuser: TCT